### ISSUE TITLE
units for electric vehicle efficiency

### ISSUE THREAD

**Issue by philblackwood** [semanticarts/gistReferenceData#28]
include common units for electric vehicle efficiency. Use amount of electricity per distance and omit the inverses.

**Comment by MichaelSullivanArchitect** [comment]
I just learned that Europeans do indeed measure EV energy efficiency differently that in the US. They use **kWh/100km** whereas the US uses **kWh/mile**. Ah well, I was hoping that wasn't the case but it is.

**Comment by philblackwood** [comment]
Some homework:

1 watt hour = 3600.0 x kilogram meterSquared per secondSquared

1 watt hour per meter = 3600.0 x kilogram meterSquared per meter secondSquared   (same conversion factor)

1 kilowatt hour per kilometer = 3600.0 x kilogram meterSquared per meter secondSquared   (same conversion factor)

1 kilowatt hour per 100 kilometers = 36.0 x kilogram meterSquared per meter secondSquared   (same conversion factor)

1 watt hour per kilometer = 3.6 x kilogram meterSquared per meter secondSquared

1 watt hour per mile = tbd

Will use the query createNewUnit2.rq to validate the above and form the variations on this.

All will be of the form:   energy per distance.  (none will be distance per energy)

**Comment by MichaelSullivanArchitect** [comment]
so which is primary and which is the inverse? I would assume the EU pattern would be primary? e.g. distance per energy

**Comment by philblackwood** [comment]
@MichaelSullivanArchitect  Metrics experts say the preferred way to express electric vehicle efficiency is amount of electricity per distance, like kwh/mile or kwh/100miles or kwh/100km.

The miles per gallon equivalent will go under gistd:_Aspect_inverse_electric_vehicle_efficiency.

To convert from one to the other, convert to base SI units, then take the inverse, then convert to new units.

**Comment by MichaelSullivanArchitect** [comment]
the above should read "...**the amount of electric energy per distance**..." -- not the amount of electricity. (i.e. the small the number, the more efficient the vehicle is)
